= ドキュメント作成システム構築ガイド
:doctype: book
:source-highlighter: coderay
:listing-caption: Listing
:pdf-page-size: Letter
:toc: right
:toc-title: 目次
:toclevels: 4
:imagesdir: ./images

// The following configuration is a hack that keeps Asciidoctor from generating TOC for every AsciiDoc enabled table cells.
:toc!:

== まえがき
本書はドキュメントを効率的に作成する方法について解説します。効率化のために、ソフトウェア開発で利用されるツール群を組みあわせて使用します。

本書は2部構成です。1部は、必要なツール群のセットアップと小規模なドキュメント作成について解説します。1章で本書の目的について解説します。2章で必要なツール群のセットアップと、初歩的な使い方について解説します。3章では、Markdownというシンプルなマークアップ言語を紹介します。4章は、バージョン管理システムを利用した履歴管理と共同作業について事例をまじえて解説します。5章では、ドキュメント検査ツールRedPenの設定と詳細な使い方について紹介します。

2部では大規模なドキュメント作成で利用するツール群について解説します。6章でAsciiDocというフォーマットについて解説します。7章では、ドキュメント生成ツールを使って、PDFやEPUBなど人が読みやすいフォーマットに変換してみます。8章では、スタイルの調整方法について解説します。9章では、本書籍で解説したツール群を組み合わせた、ドキュメントの作成システムについて解説します。

サンプルのダウンロード::
本書で解説された設定や、サンプルドキュメントはlink:https://github.com/continuous-manual-writing/sample[]にあります。本の内容を理解する手助けとなりますので、ぜひご利用ください。

対象とする読者::
本書が対象とする読者はドキュメントを作成している、もしくはドキュメント作成に興味がある方全員です。ドキュメントの内容は仕様書でも、製品のマニュアルでもかまいません。しかし一部の解説でUNIXコマンドを利用しているため、コマンドをつかったことがないと理解できない箇所があります。UNIXコマンドを触ったことがない人は、本書のまえに「UNIXコマンドブック（<<伊藤ら>>）」を読むとよいでしょう。

用語::

**ドキュメント**::

本書では、**ドキュメント**を技術文書の総称として使用します。ドキュメントの種類については1章を参照してください。

**ツール、ソフトウェア**::

本書ではソフトウェア群を**ツール**とよびます。**ソフトウェア**は「ソフトウェア開発では」という開発の文脈で利用します。

**システム**::

システムはツールを組みあわせて作成される環境を指します。本書では、システムというとドキュメント作成システムを指します。ただし**バージョン管理システム**のように一般的にシステムと呼称される用語は、そのままシステムと呼びます。

== 第1部 ドキュメンテーション入門

第1部ではドキュメントの作成に利用できるツールの紹介します。その後小規模なドキュメントの作成をとおして、紹介するツールの利用法について理解を深めます。

=== 第1章 モダンなドキュメント開発

[[chap1, 1章]]
include::chapter1.adoc[]

[[chap2, 2章]]
include::dummy.adoc[]

[[chap3, 3章]]
include::dummy.adoc[]

[[chap4, 4章]]
include::dummy.adoc[]

[[chap5, 5章]]
include::dummy.adoc[]

[[chap6, 6章]]
include::dummy.adoc[]

[[chap7, 7章]]
include::dummy.adoc[]

[[chap8, 8章]]
include::dummy.adoc[]

[[chap9, 9章]]
include::dummy.adoc[]

include::bibliography.adoc[]
